import { ResourceDescriptor } from '../types';

const RESOURCE_TYPE_OPTIONS = [
  { name: 'Configuration', value: 'configurations' },
  { name: 'Contact', value: 'contacts' },
  { name: 'Document', value: 'documents' },
  { name: 'Domain', value: 'domains' },
  { name: 'Location', value: 'locations' },
  { name: 'Password', value: 'passwords' },
  { name: 'Flexible Asset', value: 'flexible_assets' },
  { name: 'SSL Certificate', value: 'ssl_certificates' },
  { name: 'Checklist', value: 'checklists' },
  { name: 'Checklist Template', value: 'checklist_templates' },
  { name: 'Ticket', value: 'tickets' },
];

export const descriptor: ResourceDescriptor = {
  name: 'attachment',
  displayName: 'Attachment',
  jsonApiType: 'attachments',
  endpoint: 'attachments',
  special: 'attachments',
  idParam: 'attachmentId',
  operations: ['getAll', 'get', 'create', 'update', 'delete', 'bulkDelete'],
  fields: [
    {
      name: 'resourceType',
      attribute: 'resource-type',
      displayName: 'Resource Type',
      type: 'options',
      options: RESOURCE_TYPE_OPTIONS,
      required: true,
      onOperations: ['getAll', 'get', 'create', 'update', 'delete', 'bulkDelete'],
      description: 'The type of the parent resource this attachment belongs to',
    },
    {
      name: 'resourceId',
      attribute: 'resource-id',
      displayName: 'Resource ID',
      type: 'string',
      required: true,
      onOperations: ['getAll', 'get', 'create', 'update', 'delete', 'bulkDelete'],
      description: 'The ID of the parent resource',
    },
    {
      name: 'fileName',
      attribute: 'file-name',
      displayName: 'File Name',
      type: 'string',
      onOperations: ['create'],
      description: 'The file name for the attachment',
    },
    {
      name: 'fileBase64',
      attribute: 'file-base-64',
      displayName: 'File Base64',
      type: 'string',
      onOperations: ['create'],
      description: 'Base64-encoded file content (or set Binary Property Name instead)',
    },
    {
      name: 'binaryPropertyName',
      attribute: 'binary-property-name',
      displayName: 'Binary Property Name',
      type: 'string',
      onOperations: ['create'],
      description: 'Name of the n8n binary property to upload (alternative to File Base64)',
    },
    {
      name: 'name',
      attribute: 'name',
      displayName: 'Name',
      type: 'string',
      onOperations: ['update'],
      description: 'The display name of the attachment',
    },
    {
      name: 'attachmentIds',
      attribute: 'attachment-ids',
      displayName: 'Attachment IDs',
      type: 'json',
      default: '[]',
      onOperations: ['bulkDelete'],
      description: 'JSON array of attachment IDs to delete in bulk',
    },
  ],
};
