import { ResourceDescriptor } from '../types';

export const descriptor: ResourceDescriptor = {
  name: 'configuration',
  displayName: 'Configuration',
  jsonApiType: 'configurations',
  endpoint: 'configurations',
  operations: ['getAll', 'get', 'create', 'update', 'delete', 'bulkUpdate'],
  orgScoped: true,
  fields: [
    {
      name: 'name',
      attribute: 'name',
      displayName: 'Name',
      type: 'string',
      required: true,
      onOperations: ['create', 'update'],
      description: 'The configuration name',
    },
    // organizationId is auto-emitted by the orgScoped block in
    // buildResourceProperties (create/getAll); an explicit field here
    // would collide with the reserved-name guard.
    {
      name: 'configurationTypeId',
      attribute: 'configuration-type-id',
      displayName: 'Configuration Type',
      type: 'options',
      loadOptionsMethod: 'getConfigurationTypes',
      onOperations: ['create', 'update'],
      description: 'The configuration type',
    },
    {
      name: 'configurationStatusId',
      attribute: 'configuration-status-id',
      displayName: 'Configuration Status',
      type: 'options',
      loadOptionsMethod: 'getConfigurationStatuses',
      onOperations: ['create', 'update'],
      description: 'The configuration status',
    },
    {
      name: 'serialNumber',
      attribute: 'serial-number',
      displayName: 'Serial Number',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'The serial number of the configuration',
    },
    {
      name: 'assetTag',
      attribute: 'asset-tag',
      displayName: 'Asset Tag',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'The asset tag of the configuration',
    },
    {
      name: 'primaryIp',
      attribute: 'primary-ip',
      displayName: 'Primary IP',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'The primary IP address of the configuration',
    },
    {
      name: 'macAddress',
      attribute: 'mac-address',
      displayName: 'MAC Address',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'The MAC address of the configuration',
    },
    {
      name: 'hostname',
      attribute: 'hostname',
      displayName: 'Hostname',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'The hostname of the configuration',
    },
    {
      name: 'notes',
      attribute: 'notes',
      displayName: 'Notes',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'Notes about the configuration',
    },
    {
      name: 'archived',
      attribute: 'archived',
      displayName: 'Archived',
      type: 'boolean',
      default: false,
      onOperations: ['create', 'update'],
      description: 'Whether the configuration is archived',
    },
  ],
  filters: [
    {
      name: 'name',
      attribute: 'name',
      displayName: 'Name',
      type: 'string',
      description: 'Filter by configuration name',
    },
    {
      name: 'organizationId',
      attribute: 'organization-id',
      displayName: 'Organization ID',
      type: 'string',
      description: 'Filter by organization ID',
    },
    {
      name: 'configurationTypeId',
      attribute: 'configuration-type-id',
      displayName: 'Configuration Type ID',
      type: 'string',
      description: 'Filter by configuration type ID',
    },
    {
      name: 'serialNumber',
      attribute: 'serial-number',
      displayName: 'Serial Number',
      type: 'string',
      description: 'Filter by serial number',
    },
    {
      name: 'archived',
      attribute: 'archived',
      displayName: 'Archived',
      type: 'boolean',
      description: 'Filter by archived status',
    },
  ],
  includes: ['configuration_interfaces', 'attachments', 'passwords', 'related_items', 'recent_versions'],
};
