import { ResourceDescriptor } from '../types';

export const descriptor: ResourceDescriptor = {
  name: 'contact',
  displayName: 'Contact',
  jsonApiType: 'contacts',
  endpoint: 'contacts',
  operations: ['getAll', 'get', 'create', 'update', 'delete', 'bulkDelete'],
  orgScoped: true,
  fields: [
    {
      name: 'organizationId',
      attribute: 'organization-id',
      displayName: 'Organization',
      type: 'options',
      loadOptionsMethod: 'getOrganizations',
      onOperations: ['create', 'update'],
      description: 'The organization this contact belongs to',
    },
    {
      name: 'firstName',
      attribute: 'first-name',
      displayName: 'First Name',
      type: 'string',
      required: true,
      onOperations: ['create', 'update'],
      description: 'The contact first name',
    },
    {
      name: 'lastName',
      attribute: 'last-name',
      displayName: 'Last Name',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'The contact last name',
    },
    {
      name: 'title',
      attribute: 'title',
      displayName: 'Title',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'The contact job title',
    },
    {
      name: 'contactTypeId',
      attribute: 'contact-type-id',
      displayName: 'Contact Type',
      type: 'options',
      loadOptionsMethod: 'getContactTypes',
      onOperations: ['create', 'update'],
      description: 'The contact type',
    },
    {
      name: 'notes',
      attribute: 'notes',
      displayName: 'Notes',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'Notes about the contact',
    },
    {
      name: 'important',
      attribute: 'important',
      displayName: 'Important',
      type: 'boolean',
      default: false,
      onOperations: ['create', 'update'],
      description: 'Whether this contact is marked as important',
    },
  ],
  filters: [
    {
      name: 'organizationId',
      attribute: 'organization-id',
      displayName: 'Organization ID',
      type: 'string',
      description: 'Filter by organization ID',
    },
    {
      name: 'firstName',
      attribute: 'first-name',
      displayName: 'First Name',
      type: 'string',
      description: 'Filter by first name',
    },
    {
      name: 'lastName',
      attribute: 'last-name',
      displayName: 'Last Name',
      type: 'string',
      description: 'Filter by last name',
    },
  ],
};
