import { ResourceDescriptor } from '../types';

export const descriptor: ResourceDescriptor = {
  name: 'organization',
  displayName: 'Organization',
  jsonApiType: 'organizations',
  endpoint: 'organizations',
  operations: ['getAll', 'get', 'create', 'update', 'delete', 'bulkDelete'],
  fields: [
    {
      name: 'name',
      attribute: 'name',
      displayName: 'Name',
      type: 'string',
      required: true,
      onOperations: ['create', 'update'],
      description: 'The organization name',
    },
    {
      name: 'description',
      attribute: 'description',
      displayName: 'Description',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'A description of the organization',
    },
    {
      name: 'organizationTypeId',
      attribute: 'organization-type-id',
      displayName: 'Organization Type',
      type: 'options',
      loadOptionsMethod: 'getOrganizationTypes',
      onOperations: ['create', 'update'],
      description: 'The organization type',
    },
    {
      name: 'organizationStatusId',
      attribute: 'organization-status-id',
      displayName: 'Organization Status',
      type: 'options',
      loadOptionsMethod: 'getOrganizationStatuses',
      onOperations: ['create', 'update'],
      description: 'The organization status',
    },
    {
      name: 'quickNotes',
      attribute: 'quick-notes',
      displayName: 'Quick Notes',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'Quick notes for the organization',
    },
    {
      name: 'alert',
      attribute: 'alert',
      displayName: 'Alert',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'An alert message for the organization',
    },
  ],
  filters: [
    {
      name: 'name',
      attribute: 'name',
      displayName: 'Name',
      type: 'string',
      description: 'Filter by organization name',
    },
    {
      name: 'organizationTypeId',
      attribute: 'organization-type-id',
      displayName: 'Organization Type ID',
      type: 'string',
      description: 'Filter by organization type ID',
    },
    {
      name: 'organizationStatusId',
      attribute: 'organization-status-id',
      displayName: 'Organization Status ID',
      type: 'string',
      description: 'Filter by organization status ID',
    },
  ],
};
