import { ResourceDescriptor } from '../types';

export const descriptor: ResourceDescriptor = {
  name: 'password',
  displayName: 'Password',
  jsonApiType: 'passwords',
  endpoint: 'passwords',
  special: 'passwords',
  idParam: 'passwordId',
  orgScoped: true,
  operations: ['getAll', 'get', 'create', 'update', 'delete', 'archive', 'restore', 'getVersions', 'getVersion'],
  fields: [
    // name/username/password/url/notes/category/folder/restricted/otp are handled via ATTRIBUTE_MAP in handler
    {
      name: 'name',
      attribute: 'name',
      displayName: 'Name',
      type: 'string',
      required: true,
      onOperations: ['create', 'update'],
      description: 'The password name',
    },
    {
      name: 'username',
      attribute: 'username',
      displayName: 'Username',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'The username associated with this password',
    },
    {
      name: 'password',
      attribute: 'password',
      displayName: 'Password',
      type: 'string',
      password: true,
      onOperations: ['create', 'update'],
      description: 'The password value',
    },
    {
      name: 'url',
      attribute: 'url',
      displayName: 'URL',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'The URL associated with this password',
    },
    {
      name: 'notes',
      attribute: 'notes',
      displayName: 'Notes',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'Notes about this password',
    },
    {
      name: 'passwordCategoryId',
      attribute: 'password-category-id',
      displayName: 'Password Category',
      type: 'options',
      loadOptionsMethod: 'getPasswordCategories',
      onOperations: ['create', 'update'],
      description: 'The password category',
    },
    {
      name: 'passwordFolderId',
      attribute: 'password-folder-id',
      displayName: 'Password Folder ID',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'IT Glue password folder ID (optional)',
    },
    {
      name: 'restricted',
      attribute: 'restricted',
      displayName: 'Restricted',
      type: 'boolean',
      default: false,
      onOperations: ['create', 'update'],
      description: 'Whether this password is restricted to certain users',
    },
    {
      name: 'otpSecret',
      attribute: 'otp-secret',
      displayName: 'OTP Secret',
      type: 'string',
      password: true,
      onOperations: ['create', 'update'],
      description: 'The OTP/TOTP secret for this password',
    },
    {
      name: 'otpEnabled',
      attribute: 'otp-enabled',
      displayName: 'OTP Enabled',
      type: 'boolean',
      default: false,
      onOperations: ['create', 'update'],
      description: 'Whether one-time-password (OTP) is enabled for this password',
    },
    {
      name: 'resourceUrl',
      attribute: 'resource-url',
      displayName: 'Resource URL',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'URL of the IT Glue resource this password is associated with',
    },
    // versionId: used as path param for getVersion operation
    {
      name: 'versionId',
      attribute: 'version-id',
      displayName: 'Version ID',
      type: 'string',
      onOperations: ['getVersion'],
      description: 'The ID of the password version to retrieve',
    },
    // revealPlaintext: security gate field — never settable by AI
    {
      name: 'revealPlaintext',
      attribute: 'reveal-plaintext',
      displayName: 'Reveal Plaintext',
      type: 'boolean',
      default: false,
      onOperations: ['get', 'getVersion'],
      hideFromAITool: true,
      description: 'Author-only: reveal the plaintext password. IGNORED when the node runs as an AI/agent tool (fail-closed). Never settable by AI.',
    },
    // passwordId is auto-emitted by buildResourceProperties for every
    // single-record op (get/update/delete/archive/restore/getVersions);
    // an explicit field here would collide with the reserved-name guard.
  ],
  filters: [
    {
      name: 'name',
      attribute: 'name',
      displayName: 'Name',
      type: 'string',
      description: 'Filter by password name',
    },
    {
      name: 'organizationId',
      attribute: 'organization-id',
      displayName: 'Organization ID',
      type: 'string',
      description: 'Filter by organization ID',
    },
    {
      name: 'archived',
      attribute: 'archived',
      displayName: 'Archived',
      type: 'boolean',
      description: 'Filter by archived status',
    },
  ],
  includes: ['attachments', 'related_items', 'recent_versions'],
};
