import { ResourceDescriptor } from '../types';

const RESOURCE_TYPE_OPTIONS = [
  { name: 'Configuration', value: 'configurations' },
  { name: 'Contact', value: 'contacts' },
  { name: 'Document', value: 'documents' },
  { name: 'Domain', value: 'domains' },
  { name: 'Location', value: 'locations' },
  { name: 'Password', value: 'passwords' },
  { name: 'Flexible Asset', value: 'flexible_assets' },
  { name: 'SSL Certificate', value: 'ssl_certificates' },
  { name: 'Checklist', value: 'checklists' },
  { name: 'Checklist Template', value: 'checklist_templates' },
  { name: 'Ticket', value: 'tickets' },
];

const DESTINATION_TYPE_OPTIONS = [
  { name: 'Configuration', value: 'Configuration' },
  { name: 'Contact', value: 'Contact' },
  { name: 'Document', value: 'Document' },
  { name: 'Domain', value: 'Domain' },
  { name: 'Location', value: 'Location' },
  { name: 'Organization', value: 'Organization' },
  { name: 'Password', value: 'Password' },
  { name: 'SSL Certificate', value: 'SslCertificate' },
  { name: 'Flexible Asset', value: 'FlexibleAsset' },
];

export const descriptor: ResourceDescriptor = {
  name: 'relatedItem',
  displayName: 'Related Item',
  jsonApiType: 'related_items',
  endpoint: 'related_items',
  special: 'relatedItems',
  idParam: 'relatedItemId',
  operations: ['create', 'update', 'bulkDelete'],
  fields: [
    {
      name: 'resourceType',
      attribute: 'resource-type',
      displayName: 'Resource Type',
      type: 'options',
      options: RESOURCE_TYPE_OPTIONS,
      required: true,
      onOperations: ['create', 'update', 'bulkDelete'],
      description: 'The type of the source resource for this relationship',
    },
    {
      name: 'resourceId',
      attribute: 'resource-id',
      displayName: 'Resource ID',
      type: 'string',
      required: true,
      onOperations: ['create', 'update', 'bulkDelete'],
      description: 'The ID of the source resource',
    },
    {
      name: 'destinationId',
      attribute: 'destination-id',
      displayName: 'Destination ID',
      type: 'string',
      required: true,
      onOperations: ['create'],
      description: 'The ID of the destination resource to relate to',
    },
    {
      name: 'destinationType',
      attribute: 'destination-type',
      displayName: 'Destination Type',
      type: 'options',
      options: DESTINATION_TYPE_OPTIONS,
      required: true,
      onOperations: ['create'],
      description: 'The type of the destination resource',
    },
    {
      name: 'notes',
      attribute: 'notes',
      displayName: 'Notes',
      type: 'string',
      onOperations: ['create', 'update'],
      description: 'Notes about this relationship',
    },
    {
      name: 'relatedItemIds',
      attribute: 'related-item-ids',
      displayName: 'Related Item IDs',
      type: 'json',
      default: '[]',
      onOperations: ['bulkDelete'],
      description: 'JSON array of related item IDs to delete in bulk',
    },
  ],
};
