/**
 * scripts/gen-docs.ts
 *
 * Docs generator for n8n-nodes-itglue-extended.
 * Run: npx ts-node scripts/gen-docs.ts
 *      (or: npm run docs)
 *
 * Writes:
 *   docs/resources/<resource.name>.md  — one per enabledResources entry
 *   docs/resources/README-matrix.md    — full registry table (enabled + gated)
 */

import * as fs from 'fs';
import * as path from 'path';

// We import directly from the registry source (CommonJS via ts-node)
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { registry, enabledResources } = require('../nodes/ITGlue/registry/index') as {
  registry: import('../nodes/ITGlue/registry/types').ResourceDescriptor[];
  enabledResources: import('../nodes/ITGlue/registry/types').ResourceDescriptor[];
};

import type { ResourceDescriptor, OperationName } from '../nodes/ITGlue/registry/types';

// ─── helpers ─────────────────────────────────────────────────────────────────

const DOCS_DIR = path.resolve(__dirname, '..', 'docs', 'resources');

/** Human-readable description for each operation */
const OPERATION_DESCRIPTIONS: Record<OperationName, string> = {
  getAll: 'List / search all records (paginated)',
  get: 'Retrieve a single record by ID',
  create: 'Create a new record',
  update: 'Update an existing record',
  delete: 'Delete a record by ID',
  bulkUpdate: 'Update multiple records in a single request',
  bulkDelete: 'Delete multiple records in a single request',
  archive: 'Archive / soft-delete a record',
  restore: 'Restore an archived record',
  getVersions: 'List all revision versions of a record',
  getVersion: 'Retrieve a specific revision version',
  createAndWait: 'Create and wait for completion (async)',
  publish: 'Publish a draft record',
};

function mdEscape(s: string): string {
  return (s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function operationsList(ops: OperationName[]): string {
  return ops.map(o => `\`${o}\``).join(', ');
}

function specialBadge(r: ResourceDescriptor): string {
  if (!r.special) return '';
  return `\n> **Special handler:** \`${r.special}\` — uses a custom request pipeline instead of the generic CRUD engine.\n`;
}

function orgScopedNote(r: ResourceDescriptor): string {
  if (!r.orgScoped) return '';
  return '\n> **Organisation-scoped:** The node offers a "Scope to Organisation" toggle for this resource. When enabled, requests are prefixed with `/organizations/{id}/`.\n';
}

// ─── per-resource doc ─────────────────────────────────────────────────────────

function buildResourceDoc(r: ResourceDescriptor): string {
  const lines: string[] = [];

  lines.push(`# ${r.displayName}`);
  lines.push('');
  lines.push(`> Generated by \`scripts/gen-docs.ts\`. Do not edit manually — re-run \`npm run docs\` to regenerate.`);
  lines.push('');
  lines.push(`| Property | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| **Resource name** | \`${r.name}\` |`);
  lines.push(`| **JSON:API type** | \`${r.jsonApiType}\` |`);
  lines.push(`| **Endpoint** | \`/${r.endpoint}\` |`);
  if (r.idParam) {
    lines.push(`| **ID param** | \`${r.idParam}\` |`);
  }
  if (r.special) {
    lines.push(`| **Special handler** | \`${r.special}\` |`);
  }
  if (r.orgScoped) {
    lines.push(`| **Org-scoped** | Yes |`);
  }
  lines.push('');

  // special/orgScoped callouts
  lines.push(specialBadge(r).trim());
  lines.push(orgScopedNote(r).trim());
  if (r.special || r.orgScoped) lines.push('');

  // Operations table
  lines.push(`## Operations`);
  lines.push('');
  lines.push(`| Operation | Description |`);
  lines.push(`|---|---|`);
  for (const op of r.operations) {
    lines.push(`| \`${op}\` | ${OPERATION_DESCRIPTIONS[op] ?? op} |`);
  }
  lines.push('');

  // Fields table
  const sortedFields = [...r.fields].sort((a, b) => a.name.localeCompare(b.name));
  if (sortedFields.length > 0) {
    lines.push(`## Fields`);
    lines.push('');
    lines.push(`| n8n Param | JSON:API Attribute | Type | Required | On Operations | Description |`);
    lines.push(`|---|---|---|---|---|---|`);
    for (const f of sortedFields) {
      const req = f.required ? 'Yes' : 'No';
      const ops = f.onOperations ? f.onOperations.map(o => `\`${o}\``).join(', ') : '`create`, `update`';
      const desc = mdEscape(f.description ?? '');
      const secretNote = f.secret ? ' *(secret — redacted in AI/tool responses)*' : f.password ? ' *(masked input)*' : '';
      lines.push(`| \`${f.name}\` | \`${f.attribute}\` | \`${f.type}\` | ${req} | ${ops} | ${mdEscape(desc)}${secretNote} |`);
    }
    lines.push('');
  }

  // Filters table
  if (r.filters && r.filters.length > 0) {
    const sortedFilters = [...r.filters].sort((a, b) => a.name.localeCompare(b.name));
    lines.push(`## Filters`);
    lines.push('');
    lines.push(`Available on the \`getAll\` operation via the **Filters** parameter.`);
    lines.push('');
    lines.push(`| Filter Name | JSON:API Attribute | Type | Description |`);
    lines.push(`|---|---|---|---|`);
    for (const f of sortedFilters) {
      lines.push(`| \`${f.name}\` | \`${f.attribute}\` | \`${f.type}\` | ${mdEscape(f.description ?? '')} |`);
    }
    lines.push('');
  }

  // Includes
  if (r.includes && r.includes.length > 0) {
    lines.push(`## Includes (side-loads)`);
    lines.push('');
    lines.push(`Pass one or more of the following values in the **Include** parameter to side-load related data in the same response:`);
    lines.push('');
    for (const inc of r.includes) {
      lines.push(`- \`${inc}\``);
    }
    lines.push('');
  }

  // AI tool note
  lines.push(`## Using with AI Agents`);
  lines.push('');
  lines.push(`This node is \`usableAsTool: true\`. When invoked from an AI/agent workflow the node behaves identically to a manual workflow, **except**:`);
  lines.push('');
  lines.push(`- **Passwords are fail-closed.** Any field marked as a secret (e.g. \`revealPlaintext\`) is ignored when the node is running as a tool — plaintext secrets are never returned to an AI agent regardless of field values.`);
  lines.push(`- Agents can create, update, rotate, and delete records normally.`);
  lines.push(`- Safe agent prompt example: *"Find the ${r.displayName.toLowerCase()} named X in org Y"*`);
  lines.push('');

  return lines.filter(l => l !== 'undefined' && l !== undefined).join('\n');
}

// ─── README matrix ───────────────────────────────────────────────────────────

function buildMatrix(
  allResources: ResourceDescriptor[],
  enabled: ResourceDescriptor[],
): string {
  const enabledNames = new Set(enabled.map(r => r.name));
  const sorted = [...allResources].sort((a, b) => a.displayName.localeCompare(b.displayName));

  const lines: string[] = [];
  lines.push(`# IT Glue Resource Matrix`);
  lines.push('');
  lines.push(`> Generated by \`scripts/gen-docs.ts\`. Do not edit manually.`);
  lines.push('');
  lines.push(`This table covers every resource in the registry. **Enabled** resources are active in the node UI. **Verification-pending** resources are implemented but excluded from the node UI until their endpoints have been confirmed against the live IT Glue API.`);
  lines.push('');
  lines.push(`| Resource | Endpoint | Operations | Status |`);
  lines.push(`|---|---|---|---|`);
  for (const r of sorted) {
    const status = enabledNames.has(r.name)
      ? '✅ enabled'
      : '⏳ verification-pending';
    const ops = operationsList(r.operations);
    const docLink = enabledNames.has(r.name)
      ? `[${r.displayName}](./${r.name}.md)`
      : r.displayName;
    lines.push(`| ${docLink} | \`/${r.endpoint}\` | ${ops} | ${status} |`);
  }
  lines.push('');

  const enabledCount = enabled.length;
  const pendingCount = allResources.length - enabledCount;
  lines.push(`**${enabledCount} enabled** · **${pendingCount} verification-pending**`);
  lines.push('');

  return lines.join('\n');
}

// ─── main ─────────────────────────────────────────────────────────────────────

function main(): void {
  fs.mkdirSync(DOCS_DIR, { recursive: true });

  // Sort enabled resources by displayName for stable, deterministic output
  const sortedEnabled = [...(enabledResources as ResourceDescriptor[])].sort((a, b) =>
    a.displayName.localeCompare(b.displayName),
  );

  let writtenDocs = 0;
  for (const r of sortedEnabled) {
    const content = buildResourceDoc(r);
    const outPath = path.join(DOCS_DIR, `${r.name}.md`);
    fs.writeFileSync(outPath, content, 'utf8');
    writtenDocs++;
  }

  // Matrix covers all registry resources
  const matrixContent = buildMatrix(registry as ResourceDescriptor[], enabledResources as ResourceDescriptor[]);
  const matrixPath = path.join(DOCS_DIR, 'README-matrix.md');
  fs.writeFileSync(matrixPath, matrixContent, 'utf8');

  const totalRegistry = (registry as ResourceDescriptor[]).length;
  const gatedCount = totalRegistry - (enabledResources as ResourceDescriptor[]).length;

  console.log(`✓ docs generator complete`);
  console.log(`  ${writtenDocs} resource docs written to docs/resources/`);
  console.log(`  docs/resources/README-matrix.md written (${totalRegistry} rows)`);
  console.log(`  ${gatedCount} gated resources listed as verification-pending in matrix`);
}

main();
